ThreeSixtyGiving/standard

360-giving-schema.json
From "What was..." to "When..."
=> Changes dateModified description

documentation/reference.md, documentation/src/reference.md
Following discussion on https://github.com/ThreeSixtyGiving/website/issues/61
=> Formats character

README.md
* Mention package schema
* Better explain what to do when making documentation changes
=> [#85][#86] Update README

documentation/src/data-protection.md
Guidance on data protection for publishers
=> data-protection.md

documentation/reference.md, documentation/src/reference.md
Realised when putting together my csv,conf slides that I got these words the opposite way around to what's conventional usage.
=> "One to many" is the phrase generally used not "many to one"

documentation/data-protection.md, documentation/licensing.md, documentation/src/data-protection.md, documentation/src/licensing.md
Adds a table of contents div to each file
Marks up titles consistently
Regenerates documentation, but we don't commit the spreadsheets
=> Improves consistency of documentation

README.md
Conflict in sync file name in the Readme.
Also, added guidance for using virtualenv with Windows.
=> Fix filename typo in README

CONTRIBUTING.md
Ben would you review this please?
=> [#170] Adds a contributing document

documentation/licensing.md, documentation/src/licensing.md
=> Removes inconsistent sentence

documentation/reference.md, documentation/src/reference.md
The URL for the data quality tool has changed
=> [#181] Rewrites the url for the data quality tool

requirements.txt
I've seleced a commit that i think works. Pls review.
=> When I treid to install I got an error on this requirement

documentation/reference.md, documentation/src/reference.md
Changed the link in src/reference.md
/reference.md is the generated version from synch_schema script
I have not committed the changed xlsx files, because they are not needed
=> [#202] Changes URL to spreadsheet templates

documentation/_templates/layout.html
http://standard.threesixtygiving.org/en/link-main-website/
=> Add link back to 360Giving main website

.gitmodules
Update docson submodule url from https://github.com/lbovet/docson to Open Data Services fork https://github.com/OpenDataServices/docson
=> Update docson submodule remote

documentation/conf.py, documentation/reference.md, requirements.txt
https://github.com/OpenDataServices/sphinxcontrib-opendataservices/
=> Move directives out to sphinxcontrib-opendataservices

documentation/_templates/layout.html
=> Linking to the Data Quality Tool from the sidemenu

documentation/identifiers.md
Hint to highlight the leading zero in company number issue to publishers, with link to 360 Website guidance.
=> #222 leading zeros in company numbers

documentation/governance.md, documentation/index.md
=> Adding governance

schema/360-giving-schema.json, schema/360-summary-table-schema.json
Branch was renamed and so lost previous Pull Request. See https://github.com/ThreeSixtyGiving/standard/pull/217
Version docs can be viewed http://standard.threesixtygiving.org/en/autumn-2017-bugfix/
=> Autumn 2017 release bugfix

schema/360-giving-schema.json
=> Changes description for duration

schema/360-summary-table-schema.json
=> Update descriptions for duration & end dates

schema/360-giving-schema.json
=> Updates description text for End Dates

documentation/getdata.md
@morchickit , @stevieflow - as promised, updated Get Data page for the standard. I'm not sure if this needs to go through a process before getting merged, so I defer to you two on that! Comments, feedback, etc welcome, of course.
=> Update Get Data page

.gitmodules, documentation/_static/css/custom.css, documentation/reference.md
Switch to 360-master branch to tracks changes in the ODSC docson fork
that are for threesixtygiving.
Fixes https://github.com/ThreeSixtyGiving/standard/issues/281
=> submodule: docson: Switch to new 360-master branch

documentation/_templates/layout.html, documentation/privacy-notice.md
We have upgraded the Matomo server for site usage analytics.
=> layout/privacy-notice: Update matomo urls

documentation/guidance/publish-data-openly.md
This updates some links. As this page is part of non-normative content, this PR can be approved without needing input from Stewardship Committee.
=> Update to links in non-normative part of guidance website

schema/360-giving-schema.json
Changes to match proposals and make consistent with other naming conventions.
=> Changes to schema titles

documentation/technical/codelists.md, documentation/technical/identifiers.md, documentation/technical/reference.md, schema/360-giving-schema.json
PR to update text to align with changes committed in PR #340
=> Updates to documentation to align with revised field titles in schema

documentation/_templates/_parts/footer.html
=> footer: Update address

documentation/guidance/index.md, documentation/guidance/making-updates.md, documentation/guidance/publish-data-openly.md, documentation/guidance/submit-data.md
Update to non-normative guidance to add new page with guidance on using the new data submission form via the DQT.
As this content is part of the non-normative guidance, this can be made live without needing to go through the Standard change management processes.
=> Kd data submission 2023

schema/360-giving-schema.json
Fixes #362 
This is to be merged into a staging branch for 1.4, which will be triggered by adding the extensions mechanism in #361. I will also edit #361 to point to the staging branch. This way we can merge the staging branch into master when #361 is approved, and thus avoid having to make separate PATCH and MINOR releases.
=> Removed unused weight properties from 360-giving-schema.json

documentation/guidance/before-starting.md, documentation/guidance/making-updates.md, documentation/guidance/publish-data-openly.md
Pull request to incorporate information about new Grantee amendments process into three pages in the non-normative part of the publisher guidance. 
As this non-normative guidance in a non-normative part of the documentation site, this doesn't need to go through the Stewardship committee approval process, so just tagging @mrshll1001 to review/check and merge when ready.
Thank you!
=> Update non-normative guidance

documentation/technical/templates-csv.md
=> technical/templates-csv.md: Fix: Correct relative URLs 
