- schema/360-giving-package-schema.json
360Giving is always 360Giving
Again, just stacking this up.
> [#68] 360Giving naming fix in the package schema

- schema/360-giving-schema.json
As suggested in https://github.com/ThreeSixtyGiving/standard/issues/123#issuecomment-190253245
I've run the `sync-schema.sh`, and as suspected this doesn't seem to change anything in the docs.
I'm suggesting removing these completely for now, as this means they won't crop up anywhere in flatten-tool's titles support, which possibly puts us in a better position to change how transactions work.
> [#123] Remove titles for transactions

- documentation/reference.md
- documentation/src/reference.md
The toc that generates the navigation on the website from these docs
is too lomg with so many options now.
By setting a few items as deeper headings we can hide them in the toc
Probably not a great thing to be editing the docs for what is really
a related application issue, but will do for now.
> Minor alteration to make the docs to accomodate toc

- documentation/src/identifiers.md
Clarified some inconsistencies in the language
Removed the section under Codes as this is about grant code classifications
and not organisation identifiers
Moved that example into the Organisation Identifiers text itself
Adds headings to the 5 steps to take to make org ids
Removes a tool tip [#124] of hidden information about internal identifiers
and places that text in the body of the page instead
This branch is based off ekoner-patch-IATI-org-register
> [#156] Rewrites the info about IATI Registration Agency list

- documentation/reference.md
- documentation/src/reference.md
- tools/build_docs.py
This aims to address Edafe's issue in #174 by introducing a step to the build_docs.py script allowing embedding of arbitrary elements of the JSON schema into the reference docs. 
I've updated src/reference.md with the appropriate markup to pull in descriptions for each sub-table.
> Addresses 174 by allowing elements of scheme to be embedded into docs

- documentation/_static/basic.css
- documentation/_templates/footer.html
- documentation/index.md
Text moved from http://www.threesixtygiving.org/standard/.
This is a page introducing a standard, so I think it belongs in the standard docs, rather than the wordpress.
Moving this means that we can also blanket redirect http://www.threesixtygiving.org/standard/ to the new standard site.
Preview of what this looks like https://threesixtygiving-standard.readthedocs.io/en/index-page/
> Add text to index page

- documentation/_templates/layout.html
#212 
Examples:
http://standard.threesixtygiving.org/en/212-hash-redirect/reference/#toc-grants-sheet
http://standard.threesixtygiving.org/en/212-hash-redirect/licensing/#toc-is-there-an-example-of-a-license-statement-
http://standard.threesixtygiving.org/en/212-hash-redirect/identifiers/#toc-organisation-identifier
http://standard.threesixtygiving.org/en/212-hash-redirect/identifiers/#toc-grant-identifier
http://standard.threesixtygiving.org/en/212-hash-redirect/identifiers/#toc-why-identifiers-matter
These all look to work except for http://standard.threesixtygiving.org/en/212-hash-redirect/licensing/#toc-is-there-an-example-of-a-license-statement-
> [#212] Rewrite old url hashes

- documentation/index.md
Was linking to the Google group, now linked to the discourse. Also change what can be done on the Github repo
> Fix links to the forum

- documentation/reference.md
Re #223  'Dots in (publisher own) field titles can cause problems'.
On the 'reference' page, beneath where it says:
> If you have additional data to report that does not fit any of the columns provided in the spreadsheet, it is okay to create your own column titles in order to report it.
I've added a _hint box_ with:
> Adding your own columns:
> If you are adding your own column titles it is best to use simple titles and to avoid special characters which could cause problems in data reuse.
>  Using only lowercase and uppercase alphabetical characters (``a-z`` and ``A-Z``), numerical digits (``0-9``) colons (``:``), parentheses (``(`` and ``)``) and single spaces will help to avoid problems. Other characters could be used, but haven't been fully tested in all possible situations.
This …
> Additional (publisher own) field titles - character usage

- requirements.txt
- schema/360-giving-schema.json
- tools/update_currency_codes.py
#109 
Please note: the schema file (360-giving-schema.json) shows a big diff due to changes in indentation/layout as a result of re-producing the file with ```json.dump()```. I don't think it is possible to preserve the previous layout using the python ```json``` module alone (it could be done using the ```tokenize``` module, but that would be kind of pointless IMO) 
'Real' changes (if any) to the schema should only affect ```schema['definitions']['currency']['enum']```, but please check when reviewing as unintended changes to the schema would obviously be quite bad.
> Add script to update currency codes in the schema

- schema/360-giving-schema.json
A bug fix as discussed on the Forum https://forum.threesixtygiving.org/t/planned-dates-duration-months-field/188
> [#186] duration (months) string to float

- requirements.txt
Update the requirements for sphinxcontrib-opendataservices so that it is
at current HEAD and includes this fix
https://github.com/OpenDataServices/sphinxcontrib-opendataservices/commit/f84eb897d1abd75f60f4dfb680130d6919982ccc
Fixes https://github.com/ThreeSixtyGiving/standard/issues/249
> requirements: Use newer version of sphinxcontrib-opendataservices

- documentation/_templates/footer.html
- documentation/_templates/layout.html
- documentation/data-protection.md
- documentation/footer.json
- documentation/getdata.md
- documentation/governance.md
- documentation/identifiers.md
- documentation/index.md
- documentation/licensing.md
- documentation/reference.md
Re-do of #267 as per discussion
Most links have been updated to https. Those that haven't have pages / documents that cause browser security warnings or are unreachable when switched to https including:
* http://org-id.guide links in `identifiers.md`
* [Licensing Open Data: A Practical Guide](http://discovery.ac.uk/files/pdf/Licensing_Open_Data_A_Practical_Guide.pdf "Licensing Open Data: A Practical Guide") in `licensing.md`
* http://sphinx-doc.org/ in `_templates/footer.html`
> Make images and links https

- requirements.txt
Read the Docs pulls in the latest version of setuptools, which the previous version of MarkupSafe was incompatible with.
> requirements: Update MarkupSafe so it installs on Read the Docs

- documentation/identifiers.md
- documentation/index.md
- documentation/licensing.md
- documentation/reference.md
- documentation/using-data.md
- schema/360-giving-package-schema.json
- schema/360-giving-schema.json
This PR updates the documentation to match the schema changes made in #305 .
> 2021-11 Documentation Update

- schema/360-giving-package-schema.json
- schema/360-giving-schema.json
PR made based on [Planio-29617](https://opendataservices.plan.io/issues/29617) as part of the housekeeping review and ahead of the SC meeting. This is for the changes to the schema only, documentation will be made in a separate pull request.
> 2021 11 schema update

- documentation/_templates/_parts/feedback.html
The link to feedback form is not ready yet so removing now and we can reinstate once it is ready.
> Removing link to feedback form

- documentation/_templates/_parts/feedback.html
The feedback form is now ready so we're able to add the form back into the footer.
> Add feedback form link

- schema/360-giving-package-schema.json
A redirect has been put in place but because the link opens directly it causes the page to open in the schema window so better to update the url.
This is a non-normative change to a normative part of the standard. As such I believe this can be approved by ODS team, once checked, without need for a patch.
As per [this policy](https://www.threesixtygiving.org/wp-content/uploads/360Giving-Standard-Policy-Normative-and-non-normative-content_final_2020-02-28.pdf)
Non-normative change within normative content
Approval of content: 360Giving
Update actioned by: 360Giving/ODSC 
Update process: Pull requests approved by a person other than the author.
> Update url to grant identifier guidance

- schema/360-giving-schema.json
A redirect has been put in place but because the link opens directly it causes the page to open in the schema window so better to update the urls - to grant and org ID guidance.
This is a non-normative change to a normative part of the standard. As such I believe this can be approved by ODS team, once checked, without need for a patch.
As per [this policy](https://www.threesixtygiving.org/wp-content/uploads/360Giving-Standard-Policy-Normative-and-non-normative-content_final_2020-02-28.pdf)
Non-normative change within normative content
Approval of content: 360Giving
Update actioned by: 360Giving/ODSC
Update process: Pull requests approved by a person other than the author.
> Update to grant and org ID guidance urls

- documentation/guidance/index.md
- documentation/guidance/location-guide.md
- documentation/guidance/plan-the-process.md
- documentation/guidance/prepare-data.md
This pull request is to add a new page with guidance on location data, and links from existing pages to the new page into the publisher guidance parts of the site. 
This is non-normative guidance being added to a non-normative section of the site, and therefore does not need SC approval to be merged.
> Adding location guidance to non-normative part of Standard docs

- documentation/technical/index.md
- documentation/technical/metadata.md
- documentation/technical/reference.md
This PATCH update will add normative guidance about metadata in 360Giving Data Standard and how to include this in 360Giving data files. 
This guidance has been written by members of the 360Giving and Open Data Services teams. I am proposing this in my capacity as member of 360Giving team, as the first stage in [PATCH approval process](https://docs.google.com/document/d/1wdHe1LXP8R0Ne-zbpb1GsJ7rBmfKCLAbsfK72vQXiOI/edit?usp=sharing), which requires sign off from 360Giving team and a member of the Stewardship committee.
> PATCH update to add normative Meta guidance to Standard docs

- documentation/technical/metadata.md
Update to correct field title from Modifield to Modified
This small update to correct a typo should be classed as a non-normative change to a normative part of the Standard - [as per the policy](https://www.threesixtygiving.org/wp-content/uploads/360Giving-Standard-Policy-Normative-and-non-normative-content_final_2020-02-28.pdf). Therefore it only needs to be approved by someone other than me. 
Matt can do you do the honours?
> Typo in Example meta sheet table

- requirements.txt
Fixes display of Recipient Ind.
Changes sheet names to be based on titles. e.g. "Actual Dates" instead of "actualDates".
See the generated spreadsheet https://standard.threesixtygiving.org/en/upgrade-flattentool/_static/summary-table/360-giving-schema-titles.xlsx
Reference page should look the same https://standard.threesixtygiving.org/en/upgrade-flattentool/technical/reference/
> requirements: Upgrade flatten-tool

- documentation/guidance/cf-guidance.md
- documentation/guidance/index.md
- documentation/guidance/location-guide.md
- documentation/guidance/prepare-data.md
- documentation/guidance/regranting.md
This PR is to add non-normative guidance on the use of **For Regrant Type** field and **For Regrant** codelist in the standard documentation. As this sits in the 'publisher guidance' parts of the doc, this can be set up and approved without reference to the Standard governance process.
As well as adding the new guidance, we've also reordered and renamed some pages in the guidance, and I've also taken the opportunity to correct a few typos/mistakes. These changes are also non-normative sections.
@mrshll1001 can you check everything is in order - raise queries, amend if needed or merge as appropriate. As per Planio issue [37424](https://opendataservices.plan.io/issues/37424)
> Non normative regranting 2023 01

- codelists/regrantType.csv
Fixes #338 
Description of FRG050 is changed from:
> Grant awarded to an organisation acting as an agent for the funder, to make grant payment on its behalf to the defined recipient(s).
to:
> Grant awarded to an organisation acting as an agent for the funder, to make grant payments on its behalf to the defined recipient(s).
Upon approval, this will be merged into `1.4-staging` for inclusion with 1.4
> Fixed description of FRG050 in regrantType.csv as per discussion

- codelists/geoCodeType.csv
Fixes #348 
Changes `Name` to `Title` to bring in line with other codelists.
This doesn't introduce any new features or backwards incompatible changes to the standard.
I think this is a PATCH because it's a backwards compatible bug fix; validation should not be affected at all and tools can expect to behave properly now.
@michaelwood does this create any problems for tooling? Thinking of the fact you mentioned it in [/grantnav/#976](https://github.com/ThreeSixtyGiving/grantnav/issues/976)
> Bring geoTypeCodelist column names in line with other codelists

- documentation/technical/metadata.md
- documentation/technical/reference.md
- schema/360-giving-package-schema.json
This PR responds to the latest SC approval that an `extensions` array is added to the 360Giving Package Schema (where metadata is):
| Property | Title | Description | Type |
|-------------|--------|--------------------|------|
|`extensions`|Extensions|An array of strings which refer to Extensions in use by this 360Giving data file. Please see the Guidance for details.| Array of Strings |
Each item in the array must be a string. I have also used `uniqueItems: true` to enforce that a publisher cannot accidentally input the same extension twice, this is to support tooling resolving things. If this is out of scope from the SC mandate, I am happy to remove this before merging.
I have confirmed:
* The changes are valid JSON
* The changes are valid JSON Schema (draft 04)
* The JSON schema …
> Add Extensions Feature

- documentation/conf.py
Some of our recent readthedocs builds have been failing, and this became evident after changes from #370 were merged and didn't appear on the live docs site.
Error log for the build is [here](https://readthedocs.org/projects/threesixtygiving-standard/builds/21753072/).
It appears to stem from some things inside `conf.py`, where a theme variable is only set when not inside the RTD environment.
I'm not sure on the details, but glancing at the pre-existing code and [this guidance](https://docs.readthedocs.io/en/stable/faq.html#how-do-i-change-behavior-when-building-with-read-the-docs), it may be that the way to detect this may have changed?
This bugfix basically removes the conditional logic and imports the theme regardless of environment. The [docs for the …
> Fix errors from conf.py for Read The Docs builds

- documentation/conf.py
- requirements.txt
This adds the fix to ensure that the readthedocs builds continue building. Build linked below:
* https://standard.threesixtygiving.org/en/eld_rtd_config_update/
> documentation/conf.py: New RTD config requirements

- documentation/_templates/base.html
Based on discussions in the internal [Planio issue](https://opendataservices.plan.io/issues/51965), the versions section from the sidebar is removed. ![image](https://github.com/user-attachments/assets/8d4a7c20-93c5-472f-88ec-d3eb34894e3b)
> Remove Versions from standard documentation sidebar

- .github/workflows/test.yml
switch to using the setup-python action's built in pip cache support, and update actions versions.
> ci: Replace deprecated actions/cache in workflow

- schema/360-giving-package-schema.json
Fixes #401
Fixed broken URL in the the `extensions` field of the package schema to point towards the correct location in the documentation
This represents a PATCH upgrade, so once we're happy that this is correct we can do the needful re notifying the SC and community.
> Fixed broken url in package schema

- .github/workflows/test.yml
Updated the github workflow for installing check-jsonschema via pip to specify verion 0.33.2, which is the latest version as of 2025-07-17.
> github: specified version for check-jsonschema

- documentation/about/governance.md
Following the decision of the Stewardship Committee on 2025-06-17, this PATCH updates the deprecation policy in the standard documentation to read as the following:
> If a term, such as a field title (known as a class or property in JSON schema) is scheduled to be renamed or removed as a result of the revision process, the next release must [deprecate](https://en.wikipedia.org/wiki/Deprecation) the term within the schema. The following MAJOR release must rename or remove the term from the schema, making it  obsolete. Data that is published  may use deprecated terms, but will receive warnings from the [360Giving Data Quality tool](https://dataquality.threesixtygiving.org/). Once obsolete, terms in published data will be treated like any other non-Standard fields.
> PATCH: Update Deprecation Policy
